export const theme = {
  colors: {
    primary: '#02D38A',
    onPrimary: '#000000',
    primaryContainer: '#005234',
    onPrimaryContainer: '#a6ffd1',
    secondary: '#000000',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#1F1F1F',
    onSecondaryContainer: '#E6E6E6',
    tertiary: '#e7c365',
    onTertiary: '#3e2e00',
    tertiaryContainer: '#c9a74d',
    onTertiaryContainer: '#503d00',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    background: '#0A0A0A',
    onBackground: '#E6E6E9',
    surface: '#0F0F0F',
    onSurface: '#E6E6E9',
    surfaceVariant: '#1F1F1F',
    onSurfaceVariant: '#CBC4D2',
    outline: '#948E9C',
    outlineVariant: '#2A2A2A',
    surfaceContainerLowest: '#050505',
    surfaceContainerLow: '#0D0D0D',
    surfaceContainer: '#121212',
    surfaceContainerHigh: '#1A1A1A',
    surfaceContainerHighest: '#242424',
    inverseSurface: '#E6E0E9',
    inverseOnSurface: '#322F35',
    inversePrimary: '#005234',
    // Custom Profile Stat Colors
    statPurple: '#CBB2FF',
    statYellow: '#E4CE5E',
    statOrange: '#E87D3E',
    badgeGreen: '#02D38A',
    timelineGrey: '#2A2731',
    achievementBg: '#D1B455',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 40,
    container_margin: 20,
    gutter: 16,
    base: 4,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  typography: {
    fontFamily: 'Inter',
    h1: {
      fontFamily: 'Inter',
      fontSize: 32,
      fontWeight: '700' as const,
      lineHeight: 38,
      letterSpacing: -0.64,
    },
    h2: {
      fontFamily: 'Inter',
      fontSize: 24,
      fontWeight: '600' as const,
      lineHeight: 31,
      letterSpacing: -0.24,
    },
    h3: {
      fontFamily: 'Inter',
      fontSize: 20,
      fontWeight: '600' as const,
      lineHeight: 28,
      letterSpacing: -0.2,
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 25,
      letterSpacing: 0,
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
      letterSpacing: 0,
    },
    bodySm: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 18,
      letterSpacing: 0,
    },
    labelCaps: {
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: '700' as const,
      lineHeight: 14,
      letterSpacing: 1.2,
      textTransform: 'uppercase' as const,
    },
    labelSm: {
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: '600' as const,
      lineHeight: 12,
      letterSpacing: 0.5,
    },
    statsDisplay: {
      fontFamily: 'Inter',
      fontSize: 40,
      fontWeight: '900' as const,
      lineHeight: 40,
      letterSpacing: -1.6,
    },
    timerDisplay: {
      fontFamily: 'Inter',
      fontSize: 64,
      fontWeight: '300' as const,
      lineHeight: 72,
      letterSpacing: -2,
      fontVariant: ['tabular-nums'] as any,
    },
    button: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '800' as const,
      lineHeight: 20,
      letterSpacing: 1.25,
      textTransform: 'uppercase' as const,
    },
  }
};
