export const theme = {
  colors: {
    primary: '#cfbcff',
    onPrimary: '#381e72',
    primaryContainer: '#6750a4',
    onPrimaryContainer: '#e0d2ff',
    secondary: '#cdc0e9',
    onSecondary: '#342b4b',
    secondaryContainer: '#4d4465',
    onSecondaryContainer: '#bfb2da',
    tertiary: '#e7c365',
    onTertiary: '#3e2e00',
    tertiaryContainer: '#c9a74d',
    onTertiaryContainer: '#503d00',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    background: '#141218',
    onBackground: '#e6e0e9',
    surface: '#141218',
    onSurface: '#e6e0e9',
    surfaceVariant: '#36343a',
    onSurfaceVariant: '#cbc4d2',
    outline: '#948e9c',
    outlineVariant: '#494551',
    surfaceContainerLowest: '#0f0d13',
    surfaceContainerLow: '#1d1b20',
    surfaceContainer: '#211f24',
    surfaceContainerHigh: '#2b292f',
    surfaceContainerHighest: '#36343a',
    inverseSurface: '#e6e0e9',
    inverseOnSurface: '#322f35',
    inversePrimary: '#6750a4',
    // Custom Profile Stat Colors
    statPurple: '#CBB2FF',
    statYellow: '#E4CE5E',
    statOrange: '#E87D3E',
    badgeGreen: '#02D38A',
    timelineGrey: '#2A2731',
    achievementBg: '#D1B455',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 40,
    container_margin: 20,
    gutter: 16,
    base: 4,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  typography: {
    fontFamily: 'Inter',
    h1: {
      fontFamily: 'Inter',
      fontSize: 32,
      fontWeight: '700' as const,
      lineHeight: 38,
      letterSpacing: -0.64,
    },
    h2: {
      fontFamily: 'Inter',
      fontSize: 24,
      fontWeight: '600' as const,
      lineHeight: 31,
      letterSpacing: -0.24,
    },
    h3: {
      fontFamily: 'Inter',
      fontSize: 20,
      fontWeight: '600' as const,
      lineHeight: 28,
      letterSpacing: -0.2,
    },
    bodyLg: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 25,
      letterSpacing: 0,
    },
    bodyMd: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
      letterSpacing: 0,
    },
    bodySm: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '400' as const,
      lineHeight: 18,
      letterSpacing: 0,
    },
    labelCaps: {
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: '700' as const,
      lineHeight: 14,
      letterSpacing: 1.2,
      textTransform: 'uppercase' as const,
    },
    labelSm: {
      fontFamily: 'Inter',
      fontSize: 10,
      fontWeight: '600' as const,
      lineHeight: 12,
      letterSpacing: 0.5,
    },
    statsDisplay: {
      fontFamily: 'Inter',
      fontSize: 40,
      fontWeight: '900' as const,
      lineHeight: 40,
      letterSpacing: -1.6,
    },
    timerDisplay: {
      fontFamily: 'Inter',
      fontSize: 64,
      fontWeight: '300' as const,
      lineHeight: 72,
      letterSpacing: -2,
      fontVariant: ['tabular-nums'] as any,
    },
    button: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '800' as const,
      lineHeight: 20,
      letterSpacing: 1.25,
      textTransform: 'uppercase' as const,
    },
  }
};
