"""Update UserBook model fields and relationships

Revision ID: 5ff87d8c622b
Revises: 652368355a50
Create Date: 2026-05-11 20:16:51.016559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ff87d8c622b'
down_revision: Union[str, Sequence[str], None] = '652368355a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_books', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_books', 'added_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user_books', 'updated_at')
    op.drop_column('user_books', 'created_at')
    # ### end Alembic commands ###
