"""add_book_title_to_sessions

Revision ID: 652368355a50
Revises: 9b3cc5c60f01
Create Date: 2026-05-08 19:32:51.925211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652368355a50'
down_revision: Union[str, Sequence[str], None] = '9b3cc5c60f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_sessions', sa.Column('book_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_sessions', 'book_title')
    # ### end Alembic commands ###
