"""make_book_id_nullable

Revision ID: 9b3cc5c60f01
Revises: 0b4383058e98
Create Date: 2026-05-07 21:41:52.907899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3cc5c60f01'
down_revision: Union[str, Sequence[str], None] = '0b4383058e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_sessions', 'book_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_sessions', 'book_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
